### ISSUE TITLE
Hire Me!

### ISSUE THREAD

**Issue by carterwonnacott** [BYUCS452F2021/GoneViral#2]
Hi, I'm Carter, and I've always said that if I were ever going to choose a career forgetting about viability, I would go into board game creation.  I'd love to be part of your team creating a pandemic-related card game.  I personally tend to prefer board games with a little more complexity, but I also love bringing more people in to the board game community, and simpler games like this tend to do the trick.

I'm not positive how you plan to develop this game, but I have experience with Android app dev and web development using Java and am interning for a company that uses languages like React and C#, if those are needed.

Thanks, and let me know if you're interested!

**Comment by edkilgore15** [comment]
I would love to have you on the team!
